services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: marksuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    # Pre-seed script is required as a volume to load mock database
    # Data inside the container is lost on restart unless you persist it with a volume.
    ports:
      - "5432:5432"

  backend:
    # TODO: you will need to add to this
    build: ./backend
    ports:
      - "3000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    # TODO: you will need to add to this

  automark:
    build: ./automark
    depends_on:
      - backend
      - db
    profiles:
      - debug
  
volumes:
  postgres_data:
